### ISSUE TITLE
Using kcSanitize method in email template

### ISSUE THREAD

**Issue by hookenful** [p2-inc/keycloak-magic-link#12]
Hi there!

Is it possible to use `kcSanitize(htmlTemplateName, ...)` method like it appears to be in default reset password template?

**Comment by xgp** [comment]
I'm not sure what that looks like. Can you show me an example of what you want?

**Comment by xgp** [comment]
Is the idea here that you want to be able to override it using message properties?

**Comment by xgp** [comment]
fixed
