### ISSUE TITLE
Missing state parameter in response from identity provider.

### ISSUE THREAD

**Issue by fabio-pereira-ubc** [p2-inc/keycloak-magic-link#15]
We are testing the keycloak-magic-link, and everything is fine when we use that in a browser flow in an IDB realm that the application connects to validate the user, as in the image below.

![image](https://user-images.githubusercontent.com/118954585/204069448-6ae3d68e-e242-4138-bcff-dad0001055ef.png)

But in our scenario, we need to provide more than one login option to our users. For that, we configure multiple identity providers in an IDB realm, and we are creating another realm for the magic link to act as an idP. The configuration is like the image below.

![image](https://user-images.githubusercontent.com/118954585/204069477-5e613373-2d12-4bde-8050-913cdff1757b.png)

These are the steps when we try to connect our example application (SP).

1) User clicks on the MLIDP idp button.
![image](https://user-images.githubusercontent.com/118954585/204067758-2d1d0b29-89b7-4d59-af20-e6a403f135d0.png)

2) User informs the email and submits it.
![image](https://user-images.githubusercontent.com/118954585/204067772-a350fb1f-9318-4602-a478-fea31a171124.png)

3) User clicks on the email received by email.
![image](https://user-images.githubusercontent.com/118954585/204067805-d905ef44-e1df-4e86-881f-e7505945e015.png)

4) User gets an error as a response
![image](https://user-images.githubusercontent.com/118954585/204067814-b62981d6-bb31-4299-b0c5-7ad12341c721.png)

To check that we have configured the idP configuration in the IDB realm and the client in the MLIDP realm, we have changed the MLIDP realm client flow to the standard browser flow, as shown in the image below. After test, we can log in successfully.

![image](https://user-images.githubusercontent.com/118954585/204069577-d83a2aac-8364-427c-a24f-918ad9575dcf.png)

There is one issue opened that the state is mentioned, but we don't know whether it is related to the issue we got.
[Magic link doesn't support PKCE or state/nonce values](https://github.com/p2-inc/keycloak-magic-link/issues/8)

The keycloak version used during tests was 18.0.1.

**Comment by xgp** [comment]
This won't work in the current implementation. Sending a request to a remote IdP requires a continuous authentication session. The magic link functionality doesn't maintain the session (even in the same browser) following the click on the email link.

Perhaps as an alternative, could you keep the magic link username form and authenticator in your forms set as `ALTERNATIVE` so that the user could click "Try another way" rather than doing it in another Realm as a remote IdP?

**Comment by fabio-pereira-ubc** [comment]
Thanks for the answer, we are going to try that!
