### ISSUE TITLE
Set form-disiplay-name, and form-help-text

### ISSUE THREAD

**Issue by ziad696** [p2-inc/keycloak-magic-link#16]
It show like this, can I change to more proper text?
![image](https://user-images.githubusercontent.com/66814551/210308679-3640ae01-5f79-4375-82aa-b031ccc1917a.png)

**Comment by xgp** [comment]
You can set these values in your messages properties file with the keys `ext-magic-form-disiplay-name`, and `ext-magic-form-help-text`. Might be a good idea to have some defaults in https://github.com/p2-inc/keycloak-magic-link/blob/main/src/main/resources/theme-resources/messages/messages_en.properties if you want to submit a PR.

**Comment by xgp** [comment]
solved by https://github.com/p2-inc/keycloak-magic-link/pull/18
thank you @ziad696

**Comment by ziad696** [comment]
welcome
