### ISSUE TITLE
New rest API link for version 20.0.2

### ISSUE THREAD

**Issue by ziad696** [p2-inc/keycloak-magic-link#17]
POST https://keycloak.host/auth/realms/test/magic-link  
is return 404 in keycloak version 20.0.2

**Comment by xgp** [comment]
After Keycloak 18, your REST URLs are relative to the `KC_HTTP_RELATIVE_PATH` variable, which defaults to empty. I'm assuming in the docs, that you are setting it to `/auth` for backwards compatibility. If you are using the new default, your URL would be `https://keycloak.host/realms/test/magic-link`.
