### ISSUE TITLE
Customizing email templates

### ISSUE THREAD

**Issue by abhilashlr7** [p2-inc/keycloak-magic-link#24]
Despite adding the magic-link-email.ftl with necessary changes, the updated template doesn't seem to be picked. What is the right way to get a custom template for this plugin to work effectively? And where should the template files be places?

**Comment by xgp** [comment]
Where are you putting that file? How are you placing it in your Keycloak deployment?

**Comment by abhilashlr7** [comment]
Ah I think I figured out somehow on getting this resolved. Now I've a related question. How do we configure the `form` that renders for magic link inside the parent `template.ftl`? What's the override for this? I tried customising `login.ftl` but that doesn't seem to be picked.

**Comment by abhilashlr7** [comment]
So when magiclink is enabled, we see the screen that asks for email address. Now, i need to add some UI elements to it and beautify it. However, I am unable to find out what's the template (file) that needs to be put up and the path that it needs to be used for customisation.

**Comment by xgp** [comment]
We use the standard [login-username](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login-username.ftl) form from the keycloak theme. You can override this by building your own custom theme. Documentation for doing that is [here](https://www.keycloak.org/docs/latest/server_development/index.html#_themes).

**Comment by abhilashlr7** [comment]
Cool. thanks for the help @xgp :)
