### ISSUE TITLE
Magic Link 'remember me' don't work

### ISSUE THREAD

**Issue by thebestgin** [p2-inc/keycloak-magic-link#25]
I just noticed that remember me does NOT work with magic links. 

I use magic link authentication for a special client
![image](https://user-images.githubusercontent.com/10037845/225898781-7585faf0-aced-4665-97ee-261a7a9c3398.png)

Remember me is enabled
![image](https://user-images.githubusercontent.com/10037845/225900787-d01135a5-d939-4065-b136-054d909a3af5.png)

When I close the Chrome browser and open it again, a new login is required.

The remember me feature also does not work with intentity providers like google. 
This is a known missing feature. 
The feature seems to be super simple to customize via custom code. 
https://keycloak.discourse.group/t/override-keycloak-class/17192/3
Maybe it can be implemented for the magic link feature as well.

**Comment by xgp** [comment]
fixed in [50f2c0e](https://github.com/p2-inc/keycloak-magic-link/commit/50f2c0e5326763d41368c2c7dc3909fd779ab43a)
