### ISSUE TITLE
EmailOtpAuthenticator does not work with "Alternative"

### ISSUE THREAD

**Issue by srt** [p2-inc/keycloak-magic-link#31]
If set to "Alternative" instead of "Required" EmailOtpAuthenticator does not succeed and returns `context.attempted()` instead of `context.success()`.

Example flow to reproduce the issue:

![image](https://github.com/p2-inc/keycloak-magic-link/assets/280415/95a5cda5-418e-4b6c-854a-172105336aaf)

**Comment by xgp** [comment]
Seems like a bug. Let me run a couple of additional use cases to figure out why I added that conditional.

**Comment by xgp** [comment]
fixed in [50f2c0e](https://github.com/p2-inc/keycloak-magic-link/commit/50f2c0e5326763d41368c2c7dc3909fd779ab43a)

**Comment by srt** [comment]
Thanks for the quick fix!
