### ISSUE TITLE
Building for Bitnami container

### ISSUE THREAD

**Issue by samuk** [p2-inc/keycloak-magic-link#34]
Docker newb here.

I grabbed the latest source from this repo.

Did a mvn clean install locally (Debian)

I then uploaded the resulting .jar to /opt/bitnami/keycloak/providers/keycloak-magic-link-0.13.jar

In docker-compose I have

`  keycloak:
    image: docker.io/bitnami/keycloak:${SOFTWARE_VERSION_TAG}
    container_name: keycloak
    restart: always
    env_file:
      - .env
    
    volumes:
    - ./keycloak-magic-link-0.13.jar:/opt/bitnami/keycloak/providers/keycloak-magic-link-0.13.jar
    ports:
      - '172.17.0.1:8080:8080'
    `

When I restart the container I get

```
ay 31 15:52:45 keycloak-ownership-clone-u4111 57c55751cd7c[2953]: #033[38;5;6mkeycloak #033[38;5;5m15:52:45.76 #033[0m#033[38;5;2mINFO #033[0m ==> ** Starting keycloak **
May 31 15:52:46 keycloak-ownership-clone-u4111 57c55751cd7c[2953]: Exception in thread "main" java.io.EOFException
May 31 15:52:46 keycloak-ownership-clone-u4111 57c55751cd7c[2953]: #011at java.base/java.io.DataInputStream.readBoolean(DataInputStream.java:250)
May 31 15:52:46 keycloak-ownership-clone-u4111 57c55751cd7c[2953]: #011at io.quarkus.bootstrap.runner.SerializedApplication.read(SerializedApplication.java:119)

```

**Comment by xgp** [comment]
This works:
```
version: '3'

services:
  keycloak:
    image: docker.io/bitnami/keycloak:21.1.1
    volumes:
      - ${PWD}/target/keycloak-magic-link-0.14-SNAPSHOT.jar:/opt/bitnami/keycloak/providers/keycloak-magic-link.jar
    environment:
      KEYCLOAK_DATABASE_VENDOR: dev-mem
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
```

**Comment by samuk** [comment]
Thanks that's helpful
I still get
`May 31 15:52:46 keycloak-ownership-clone-u4111 57c55751cd7c[2953]: Exception in thread "main" java.io.EOFException
May 31 15:52:46 keycloak-ownership-clone-u4111 57c55751cd7c[2953]: #011at java.base/java.io.DataInputStream.readBoolean(DataInputStream.java:250)
May 31 15:52:46 keycloak-ownership-clone-u4111 57c55751cd7c[2953]: #011at io.quarkus.bootstrap.runner.SerializedApplication.read(SerializedApplication.java:119)
`
It seems likely to be the way I've built the .jar. I'll try that again

**Comment by xgp** [comment]
Sorry, not able to reproduce this one.
