### ISSUE TITLE
keycloak magic link - adding update_password after successful profile submission

### ISSUE THREAD

**Issue by syama-aot** [p2-inc/keycloak-magic-link#35]
Keycloak magic link configuration doesn't have force update password option . How can i add update password after profile submission. Please help me

**Comment by xgp** [comment]
Update password is a required action that can be configured by default for new users. This is a built-in feature of Keycloak and will work with this extension. Please consult the Keycloak documentation for further information.

**Comment by syama-aot** [comment]
Thank you very much for prompt reply. But When i make update password as
default action, I am getting an issue while registration , I am getting
update password page again.
How can i avoid that.

**Comment by xgp** [comment]
The keycloak repo is a good place to ask general questions about your Keycloak setup https://github.com/keycloak/keycloak/discussions

**Comment by syama-aot** [comment]
https://github.com/p2-inc/keycloak-magic-link . This link has option of
update password on create while configuring magic link . But when deployed
phasetwo version , i am getting only force create user and update profile .
Why ?
