### ISSUE TITLE
Magic link is not showing inside Authenticator section of keycloak admin console

### ISSUE THREAD

**Issue by syama-aot** [p2-inc/keycloak-magic-link#39]
I did copied magic link jar from this repo.  https://repo1.maven.org/maven2/io/phasetwo/keycloak/keycloak-magic-link/0.14/.  I was able to do the magic link rest API, but I was unable to get that in Authenticator section. Do i need to copy any other jar along with magic link JAR. Thanks in advance

**Comment by xgp** [comment]
No. That jar should be enough. When you click "Add step" in your authentication flow, it will be in the list:

![image](https://github.com/p2-inc/keycloak-magic-link/assets/244253/bb56b2b0-51a9-49c1-95c6-e0f58b9ab0a1)

**Comment by syama-aot** [comment]
I have created a magic link with UPDATE_PASSWORD option (through the magic
link API). But it's not working. It's directly logged in.   const
magicLinkAPIUrl = config.keycloak.authUrl + '/realms/' + config.keycloak.
realmName + '/magic-link';
      const requestData = {
        email: email,
        client_id: config.keycloak.clientId,
        redirect_uri: 'http://localhost:3001/auth/redirect',
        expiration_seconds: 3600,
        force_create: true,
        // update_profile: true,
        update_password: true,
        send_email: false,
      };

      const headers = {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      };

      const response = await axios.post(magicLinkAPIUrl, requestData, {
headers }).catch(err => console.log(err));

**Comment by xgp** [comment]
Looks like a bug where it only adds the required actions when the user is new. Fix in https://github.com/p2-inc/keycloak-magic-link/pull/40

**Comment by syama-aot** [comment]
Great! Thank you very much.
