### ISSUE TITLE
Simply copy the jar in the provider in the providers folder of quay.io/keycloak/keycloak:21.1.X image leads to org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] ERROR: jakarta.ws.rs.core.UriInfo

### ISSUE THREAD

**Issue by umadnomad** [p2-inc/keycloak-magic-link#43]
Hello and thanks for this amazing provider.

- I tried it with your standalone image:
works but your standalone image is unable to import a previously exported realm.

- I went back to my "vanilla" quay.io/keycloak/keycloak:21.1.X image:
I see the providers getting loaded,
`
WARN  [org.keycloak.services] (build-37) KC-SERVICES0047: ext-magic-form...
WARN  [org.keycloak.services] (build-37) KC-SERVICES0047: ext-email-otp...
WARN  [org.keycloak.services] (build-37) KC-SERVICES0047: ext-magic-link...
`
But keycloak fails to start with ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: jakarta/ws/rs/core/UriInfo. Simply removing the jars from the providers folder made keycloak run again.

- I then tried a bitnami image and it worked.

I wonder why it doesn't work with the vanilla image.
Could you give me any insight?

Many thanks, have a nice day

**Comment by xgp** [comment]
In order to reproduce, I'd need to see the realm export file you're using. 

Sometimes loading keycloaks with changed providers creates problems importing realms, as there are provider IDs that are not recognized.

**Comment by umadnomad** [comment]
Please close this issue, I just looked in your pom and you were using ver 22, with that works, I had 21.1.2. Sorry
