### ISSUE TITLE
Prebuilt `.jar` files

### ISSUE THREAD

**Issue by hrueger** [p2-inc/keycloak-magic-link#49]
Hi,
I was looking into building the `.jar` file via GitHub actions when I discovered that the workflow is already doing that. It worked for me to download the new `.jar` from [here](https://s01.oss.sonatype.org/service/local/repositories/releases/content/io/phasetwo/keycloak/keycloak-magic-link/0.19/keycloak-magic-link-0.19.jar) (found by going to https://s01.oss.sonatype.org, searching for `keycloak magic link`, selecting the latest version, clicking on the `keycloak-magic-link-0.19.jar` in the tree at the bottom and clicking `download` on the right.
Maybe we could
a) link this page / put some docs in the readme
b) also upload that artifact to GitHub releases so it can be discovered more easily?

In my opinion this would make it easier since people don't have to install java (or hassle with Codespaces which can sometimes be a problem as we have seen) and can just download the `.jar`.

What do you think?

**Comment by xgp** [comment]
Thanks @hrueger I take for granted that people who are not familiar with java don't know to look in the maven central repo for releases https://repo1.maven.org/maven2/io/phasetwo/ 
I'll add something to the README that indicates where to find the releases.

**Comment by hrueger** [comment]
Great, thanks a lot! (I did not know about that central repo either 😉)

**Comment by xgp** [comment]
[0c00132](https://github.com/p2-inc/keycloak-magic-link/commit/0c00132f112c821f52bd3d823f7ce6ac51754e62)
