### ISSUE TITLE
Issue regarder required actions update

### ISSUE THREAD

**Issue by vanerac** [p2-inc/keycloak-magic-link#54]
I'm having an issue regarding the password update on create that triggers when even when the user already exists.
Is this normal behaviour ?

![image](https://github.com/p2-inc/keycloak-magic-link/assets/25673062/7a509f89-d6d5-400b-9d65-b452af84e0fe)
![image](https://github.com/p2-inc/keycloak-magic-link/assets/25673062/1845256c-fb2d-4293-9285-55ef1136eb8f)
![image](https://github.com/p2-inc/keycloak-magic-link/assets/25673062/7461962b-26e4-4faf-8c31-be438d324d4b)

**Comment by xgp** [comment]
@vanerac Good catch. Looks like it sets update password/profile even if the user exists. 

https://github.com/p2-inc/keycloak-magic-link/blob/main/src/main/java/io/phasetwo/keycloak/magic/MagicLink.java#L88

Please PR if you have time.

**Comment by xgp** [comment]
Thanks @vanerac !

New release will hit maven central in a few minutes once the automated release action occurs.
