### ISSUE TITLE
Default group assignment after user creation

### ISSUE THREAD

**Issue by chaselmann** [p2-inc/keycloak-magic-link#59]
I would like to assign a user to a specific group using the magic link authenticator.

A possiblie solution could be to add an addition property to the actionToken containg a groupId or a group path
and adding the user to this group in the TokenHandler.

What do you think about this approach?
If you think this is a useful feature I would also be willing to work on a pull request.

**Comment by xgp** [comment]
Feel free to create a new type of magic link Authenticator and Action Token Handler and extend these, but we are specifically trying to keep this a simple and minimal as possible.
