### ISSUE TITLE
Use in combination with multiple factors

### ISSUE THREAD

**Issue by firstdorsal** [p2-inc/keycloak-magic-link#63]
Hi, I would like to use WebAuthn or TOTP as second factor with the magic links.

Currently if i create a flow like this:
![image](https://github.com/p2-inc/keycloak-magic-link/assets/10563452/25d8fa60-c4b3-4044-a35d-bb608a63ad6e)

The second factor is just skipped instead of working with the default `Username Password Form`
![image](https://github.com/p2-inc/keycloak-magic-link/assets/10563452/9c54ea2c-fee7-455a-be08-22fa7a1e9524)

**Comment by xgp** [comment]
This implementation of Magic Links doesn't support a continuation of an existing Authentication Flow. Because it is designed to be able to be opened on a different device, it creates an entirely new authentication session when the link is opened.

**Comment by firstdorsal** [comment]
Oh okay, I would be interested to hear for what use case this would be good for.

I would have thought that MFA would be more important then to be able to open the links on other devices.

**Comment by xgp** [comment]
I think you'd probably be best served with this experiment https://github.com/stianst/keycloak-experimental/tree/main/magic-link which keeps the same session.

Thanks for your constructive opinion on what use case is most important. I'm stunned that anyone has found this extension useful.
