### ISSUE TITLE
Add force create user to Email OTP and Magic Link Continuation

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-magic-link#69]
Same as magic link

**Comment by xgp** [comment]
Per https://github.com/p2-inc/keycloak-magic-link/issues/84 also do it for Magic Link Continuation.

**Comment by alainkaiser** [comment]
@xgp Opened a small PR for the Magic Link Continuation part here:
https://github.com/p2-inc/keycloak-magic-link/pull/85

**Comment by xgp** [comment]
Done for continuation in #85

**Comment by xgp** [comment]
@rtufisi Assigning to you to do it for Email OTP.

**Comment by xgp** [comment]
Done in #100
