### ISSUE TITLE
C# Owin Application doesnt populate AuthenticationTicket

### ISSUE THREAD

**Issue by dsputnikk** [p2-inc/keycloak-magic-link#74]
I have a .Net 4.8 project. It is wrapped in Owin which is what's handling the OpenID side of things. It's effectively OpenID middleware. The integration with KC is working fine with various flows such as TOTP, 2FA SMS, Email OTP, etc but when I use magic link specifically- when the user is redirected back to my application (clearly authenticated by KC at this point) my app crashes and the only difference while debugging I can see is lack of a Owin.Context.AuthenticationTicket . This is with keycloak 23.0. 

Any ideas as to why? I'd much prefer magic link over Email OTP.

**Comment by xgp** [comment]
`Owin.Context.AuthenticationTicket` is specific to your app, and I know nothing about it. You would need to show some information about what is happening in the HTTP requests when your "app crashes". Maybe start with an example of a request that works, and one that doesn't.
