### ISSUE TITLE
How to use magic link and password parallel?

### ISSUE THREAD

**Issue by abamuc** [p2-inc/keycloak-magic-link#75]
Hi,

magic link is great, thanks for you work.

One question: I'd like to offer users different options to log in. People with password should be able to use their password, people with OTP their OTP settings, but for new people (or with forgotten password) magic link is a perfect solution.

However, I'm unable to find out how to configure that properly. Is this currently possible, and if so, how? Or does that need code? (I'd be willing to produce documentation and/or code, however am unsure if I could do that well enough for production.)

Regards,
Andi

**Comment by xgp** [comment]
Please see the documentation on Authentication Flows. Offering alternative login methods by configuring flows is detailed there, and is not specific to this extension. https://www.keycloak.org/docs/latest/server_admin/index.html#_authentication-flows
