### ISSUE TITLE
Enhancement - Request to add username attribute to the token

### ISSUE THREAD

**Issue by abhinavreddy9** [p2-inc/keycloak-magic-link#76]

**Comment by xgp** [comment]
I don't see the argument for this. The action token is for the action token handler to determine the user. The username is not necessary for that.

**Comment by abhinavreddy9** [comment]
Thanks for the clarification. I am relatively new to this and would appreciate if you can help me understand and make this change as custom implementation for my project.

Thanks in advance.

**Comment by xgp** [comment]
This is a feature request that is out of scope of this project. And no, I don't do free consulting. I will restate more severely what I implied before. If you're trying to use the token generated for the magic link for anything but the action token handler, you're doing it wrong and you should figure out another solution to your use case.

**Comment by abhinavreddy9** [comment]
I understand. Appreciate your valuable time. Thank you!
