### ISSUE TITLE
Email OTP authentication flow not available

### ISSUE THREAD

**Issue by 4abhinavjain** [p2-inc/keycloak-magic-link#77]
Hi,

I used the jar files in the pre-built [Maven](https://repo1.maven.org/maven2/io/phasetwo/keycloak/keycloak-magic-link/) repo on my official dockerized Keycloak 24.0.5 server. But only the "Magic link" flow shows up. How can I get the Email OTP authentication flow instead? Do I need to build from the source?

**Comment by xgp** [comment]
There is no pre-built, example flow for email OTP as there is for magic link. You can build your own using the email OTP authenticator. See the template here https://github.com/p2-inc/keycloak-magic-link?tab=readme-ov-file#email-otp
