### ISSUE TITLE
Rep is null on POST to magic-link

### ISSUE THREAD

**Issue by zaneGittins** [p2-inc/keycloak-magic-link#80]
Anyone seen this error before when making a POST request to magic-link? 

```
[org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: java.lang.NullPointerException: Cannot invoke "io.phasetwo.keycloak.magic.representation.MagicLinkRequest.getClientId()" because "rep" is null
```

I'm using Keycloak 24.0.4 and keycloak-magic-link-0.26, the redirect_uri and client_id are valid, and I have the manage-users role.

**Comment by xgp** [comment]
Post your full request. `rep` is the JSON body you're posting to the endpoint. That error is telling you that there is no body.

**Comment by zaneGittins** [comment]
Got it working, apologies for this issue - there was a bad character.
