### ISSUE TITLE
Question | Magic link continuation flow should be able to force user creation

### ISSUE THREAD

**Issue by alainkaiser** [p2-inc/keycloak-magic-link#84]
Hei

Once again a question from my side because I can't find the relevant information.
I could successfully setup the continuation flow. Now I wonder if it is somehow possible to force the creation of the user if the user does not yet exist? Similar to the "normal" Magic Link flow?

Thanks for your feedback!

**Comment by xgp** [comment]
Usage information here https://github.com/p2-inc/keycloak-magic-link?tab=readme-ov-file#magic-link-continuation

> The authenticator can be configured to set the expiration of the authentication flow.

If you'd like this one to support "Force Create User", and the other options supported by the original Magic Link Authenticator, please PR.

**Comment by alainkaiser** [comment]
@xgp Thanks, I saw the usage information.

I just added a small PR for "Force Create User" to be configurable also for the continuation flow. Could you please check it out? I look forward to your feedback. It's been a long time since I last used Java 😄
