### ISSUE TITLE
translations for this plugin

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-magic-link#95]
@xgp could you help me what's the supported way to create custom translations for this plugin in our own instance? I think I should create a `messages_hu.properties` and translate [this file](https://github.com/p2-inc/keycloak-magic-link/blob/main/src/main/resources/theme-resources/messages/messages_en.properties).

But where do I put this `messages_hu.properties` in the docker container?

Thanks,

_Originally posted by @vilmosnagy in https://github.com/p2-inc/keycloak-magic-link/issues/9#issuecomment-2498779779_

**Comment by xgp** [comment]
@vilmosnagy I don't have any experience putting it directly in the container. I've only done it 2 other ways:
1. building a custom distribution of this extension with the messages file in the `theme-resources/messages/` directory.
2. in another extension, put it in the `theme-resources/messages/` directory, and it should get picked up in the classpath and applied

Regarding 1, I'd take a PR with a hungarian translation, if you'd be willing to share it.

**Comment by vilmosnagy** [comment]
@xgp 

> Regarding 1, I'd take a PR with a hungarian translation, if you'd be willing to share it.

Let me do a quick research in our company, but I think we'll open a PR soon :slightly_smiling_face: Thanks for the opportunity.

One question though: as we're using kc25 at this moment, would you be willing to merge this to `xgp/25` and release it as a jar (eg.: `0.29.1`?) I'd be willing to open 2 PRs if the strings differ in any way.

**Comment by xgp** [comment]
> One question though: as we're using kc25 at this moment, would you be willing to merge this to xgp/25 and release it as a jar (eg.: 0.29.1?) I'd be willing to open 2 PRs if the strings differ in any way.

Yes.

**Comment by pnzrr** [comment]
Quick addition of translations 

@vilmosnagy perhaps you can check the Hungarian one for accuracy?

**Comment by vilmosnagy** [comment]
LGTM

**Comment by xgp** [comment]
fixed in #96
